// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pricing.Infrastructure;

#nullable disable

namespace Pricing.Infrastructure.EFCore.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    partial class PricingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pricing.Domain.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("UsageLimitPerCustomer")
                        .HasColumnType("integer");

                    b.Property<int?>("UsageLimitTotal")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EndDate");

                    b.HasIndex("Status");

                    b.ToTable("Coupons", (string)null);
                });

            modelBuilder.Entity("Pricing.Domain.CouponCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MinQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("Type");

                    b.ToTable("CouponConditions", (string)null);
                });

            modelBuilder.Entity("Pricing.Domain.CouponUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UsedAt");

                    b.ToTable("CouponUsages", (string)null);
                });

            modelBuilder.Entity("Pricing.Domain.PriceChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductPriceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductPriceId");

                    b.HasIndex("ProductPriceId", "CreatedAt");

                    b.ToTable("PriceChangeLogs", (string)null);
                });

            modelBuilder.Entity("Pricing.Domain.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId");

                    b.ToTable("ProductPrices", (string)null);
                });

            modelBuilder.Entity("Pricing.Domain.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("Pricing.Domain.PromotionAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GiftProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("GiftQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GiftVariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.HasIndex("Type");

                    b.ToTable("PromotionActions", (string)null);
                });

            modelBuilder.Entity("Pricing.Domain.PromotionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerTier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MinQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.HasIndex("Type");

                    b.ToTable("PromotionRules", (string)null);
                });

            modelBuilder.Entity("Pricing.Domain.Coupon", b =>
                {
                    b.OwnsOne("Pricing.Domain.DiscountValue", "Discount", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("DiscountAmount");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("DiscountType");

                            b1.HasKey("CouponId");

                            b1.ToTable("Coupons");

                            b1.WithOwner()
                                .HasForeignKey("CouponId");
                        });

                    b.OwnsOne("Kernel.Domain.Money", "MaxDiscountAmount", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("MaxDiscountAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("VND")
                                .HasColumnName("MaxDiscountCurrency");

                            b1.HasKey("CouponId");

                            b1.ToTable("Coupons");

                            b1.WithOwner()
                                .HasForeignKey("CouponId");
                        });

                    b.OwnsOne("Kernel.Domain.Money", "MinOrderValue", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("MinOrderValue");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("VND")
                                .HasColumnName("MinOrderCurrency");

                            b1.HasKey("CouponId");

                            b1.ToTable("Coupons");

                            b1.WithOwner()
                                .HasForeignKey("CouponId");
                        });

                    b.Navigation("Discount")
                        .IsRequired();

                    b.Navigation("MaxDiscountAmount");

                    b.Navigation("MinOrderValue");
                });

            modelBuilder.Entity("Pricing.Domain.CouponCondition", b =>
                {
                    b.HasOne("Pricing.Domain.Coupon", "Coupon")
                        .WithMany("Conditions")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("Pricing.Domain.CouponUsage", b =>
                {
                    b.HasOne("Pricing.Domain.Coupon", "Coupon")
                        .WithMany("Usages")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Kernel.Domain.Money", "DiscountApplied", b1 =>
                        {
                            b1.Property<Guid>("CouponUsageId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("DiscountApplied");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("VND")
                                .HasColumnName("DiscountAppliedCurrency");

                            b1.HasKey("CouponUsageId");

                            b1.ToTable("CouponUsages");

                            b1.WithOwner()
                                .HasForeignKey("CouponUsageId");
                        });

                    b.Navigation("Coupon");

                    b.Navigation("DiscountApplied")
                        .IsRequired();
                });

            modelBuilder.Entity("Pricing.Domain.PriceChangeLog", b =>
                {
                    b.HasOne("Pricing.Domain.ProductPrice", "ProductPrice")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("ProductPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Kernel.Domain.Money", "NewCost", b1 =>
                        {
                            b1.Property<Guid>("PriceChangeLogId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("NewCost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("VND")
                                .HasColumnName("NewCostCurrency");

                            b1.HasKey("PriceChangeLogId");

                            b1.ToTable("PriceChangeLogs");

                            b1.WithOwner()
                                .HasForeignKey("PriceChangeLogId");
                        });

                    b.OwnsOne("Kernel.Domain.Money", "NewPrice", b1 =>
                        {
                            b1.Property<Guid>("PriceChangeLogId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("NewPrice");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("VND")
                                .HasColumnName("NewPriceCurrency");

                            b1.HasKey("PriceChangeLogId");

                            b1.ToTable("PriceChangeLogs");

                            b1.WithOwner()
                                .HasForeignKey("PriceChangeLogId");
                        });

                    b.OwnsOne("Kernel.Domain.Money", "PreviousCost", b1 =>
                        {
                            b1.Property<Guid>("PriceChangeLogId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("PreviousCost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("VND")
                                .HasColumnName("PreviousCostCurrency");

                            b1.HasKey("PriceChangeLogId");

                            b1.ToTable("PriceChangeLogs");

                            b1.WithOwner()
                                .HasForeignKey("PriceChangeLogId");
                        });

                    b.OwnsOne("Kernel.Domain.Money", "PreviousPrice", b1 =>
                        {
                            b1.Property<Guid>("PriceChangeLogId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("PreviousPrice");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("VND")
                                .HasColumnName("PreviousPriceCurrency");

                            b1.HasKey("PriceChangeLogId");

                            b1.ToTable("PriceChangeLogs");

                            b1.WithOwner()
                                .HasForeignKey("PriceChangeLogId");
                        });

                    b.Navigation("NewCost")
                        .IsRequired();

                    b.Navigation("NewPrice")
                        .IsRequired();

                    b.Navigation("PreviousCost")
                        .IsRequired();

                    b.Navigation("PreviousPrice")
                        .IsRequired();

                    b.Navigation("ProductPrice");
                });

            modelBuilder.Entity("Pricing.Domain.ProductPrice", b =>
                {
                    b.OwnsOne("Kernel.Domain.Sku", "Sku", b1 =>
                        {
                            b1.Property<Guid>("ProductPriceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Sku");

                            b1.HasKey("ProductPriceId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("ProductPrices");

                            b1.WithOwner()
                                .HasForeignKey("ProductPriceId");
                        });

                    b.OwnsOne("Kernel.Domain.Money", "CurrentCost", b1 =>
                        {
                            b1.Property<Guid>("ProductPriceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("CurrentCost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("VND")
                                .HasColumnName("CurrentCostCurrency");

                            b1.HasKey("ProductPriceId");

                            b1.ToTable("ProductPrices");

                            b1.WithOwner()
                                .HasForeignKey("ProductPriceId");
                        });

                    b.OwnsOne("Kernel.Domain.Money", "CurrentPrice", b1 =>
                        {
                            b1.Property<Guid>("ProductPriceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("CurrentPrice");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("VND")
                                .HasColumnName("CurrentPriceCurrency");

                            b1.HasKey("ProductPriceId");

                            b1.ToTable("ProductPrices");

                            b1.WithOwner()
                                .HasForeignKey("ProductPriceId");
                        });

                    b.Navigation("CurrentCost")
                        .IsRequired();

                    b.Navigation("CurrentPrice")
                        .IsRequired();

                    b.Navigation("Sku")
                        .IsRequired();
                });

            modelBuilder.Entity("Pricing.Domain.PromotionAction", b =>
                {
                    b.HasOne("Pricing.Domain.Promotion", "Promotion")
                        .WithMany("Actions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Pricing.Domain.DiscountValue", "Discount", b1 =>
                        {
                            b1.Property<Guid>("PromotionActionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("DiscountAmount");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("DiscountType");

                            b1.HasKey("PromotionActionId");

                            b1.ToTable("PromotionActions");

                            b1.WithOwner()
                                .HasForeignKey("PromotionActionId");
                        });

                    b.Navigation("Discount");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Pricing.Domain.PromotionRule", b =>
                {
                    b.HasOne("Pricing.Domain.Promotion", "Promotion")
                        .WithMany("Rules")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Kernel.Domain.Money", "MinOrderValue", b1 =>
                        {
                            b1.Property<Guid>("PromotionRuleId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("MinOrderValue");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("VND")
                                .HasColumnName("MinOrderCurrency");

                            b1.HasKey("PromotionRuleId");

                            b1.ToTable("PromotionRules");

                            b1.WithOwner()
                                .HasForeignKey("PromotionRuleId");
                        });

                    b.Navigation("MinOrderValue");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Pricing.Domain.Coupon", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("Usages");
                });

            modelBuilder.Entity("Pricing.Domain.ProductPrice", b =>
                {
                    b.Navigation("ChangeLogs");
                });

            modelBuilder.Entity("Pricing.Domain.Promotion", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
