// <auto-generated />
using System;
using Inventory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.Infrastructure.EFCore.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Domain.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ThresholdWarning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Quantity");

                    b.ToTable("StockItems", t =>
                        {
                            t.HasCheckConstraint("CK_StockItem_Quantity", "\"Quantity\" >= 0");

                            t.HasCheckConstraint("CK_StockItem_ThresholdWarning", "\"ThresholdWarning\" >= 0");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.StockLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SnapshotTotalQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasFilter("\"OrderId\" IS NOT NULL");

                    b.HasIndex("StockItemId");

                    b.HasIndex("Type");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("IX_StockLog_OrderId_CreatedAt")
                        .HasFilter("\"OrderId\" IS NOT NULL");

                    b.HasIndex("StockItemId", "CreatedAt")
                        .HasDatabaseName("IX_StockLog_StockItemId_CreatedAt");

                    b.ToTable("StockLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockLog_Quantity", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_StockLog_SnapshotTotalQuantity", "\"SnapshotTotalQuantity\" >= 0");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderId", "StockItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_StockReservation_OrderId_StockItemId_Unique");

                    b.HasIndex("StockItemId", "CreatedAt");

                    b.ToTable("StockReservations", t =>
                        {
                            t.HasCheckConstraint("CK_StockReservation_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.StockItem", b =>
                {
                    b.OwnsOne("Kernel.Domain.Sku", "Sku", b1 =>
                        {
                            b1.Property<Guid>("StockItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Sku");

                            b1.HasKey("StockItemId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("StockItems");

                            b1.WithOwner()
                                .HasForeignKey("StockItemId");
                        });

                    b.Navigation("Sku")
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Domain.StockLog", b =>
                {
                    b.HasOne("Inventory.Domain.StockItem", "StockItem")
                        .WithMany()
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("Inventory.Domain.StockReservation", b =>
                {
                    b.HasOne("Inventory.Domain.StockItem", "StockItem")
                        .WithMany("Reservations")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("Inventory.Domain.StockItem", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
