global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using AutoMapper;
global using Kernel;
global using Kernel.Domain;
global using Kernel.Application;
global using Kernel.Extensions;
global using Kernel.Utilities;
global using Infrastructure;
